### ISSUE TITLE
关于`33.title_desc_textattbirnn_enc.ipynb`中导入`Attention`的问题

### ISSUE THREAD

**Issue by nicken** [cchan19/baai-zhihu-cup-2019#1]
感谢大佬的代码分享！

我在复现大佬代码是，在`33.title_desc_textattbirnn_enc.ipynb`中遇到个问题；
具体就是导入模块:
```python
from attention import Attention
```
遇到了问题

1。我尝试去 `pip install attention`
但最后遇到的是这样，表示没有这个`Attention`类
```bash
ImportError                               Traceback (most recent call last)
<ipython-input-3-7affb3597aef> in <module>
     14 from keras.layers import Embedding, Dense, Dropout, Bidirectional, CuDNNLSTM
     15 from keras.layers import Add, Subtract, Multiply, Dot
---> 16 from attention import Attention
     17 from keras import initializers, regularizers, constraints, optimizers, layers
     18 from keras.preprocessing.sequence import pad_sequences

ImportError: cannot import name 'Attention' from 'attention' (/home/hello/.pyenv/versions/3.7.7/envs/env37rec/lib/python3.7/site-packages/attention/__init__.py)
```
我也去源代码那里看了，确实是没有这个类的，因此我追踪`pypi`上的[模块](https://pypi.org/project/attention/#description)，也没能找到相关的。

因此想问，我需要如何解决这个问题？

**Comment by cchan19** [comment]
> 感谢大佬的代码分享！
> 
> 我在复现大佬代码是，在`33.title_desc_textattbirnn_enc.ipynb`中遇到个问题；
> 具体就是导入模块:
> 
> ```python
> from attention import Attention
> ```
> 
> 遇到了问题
> 
> 1。我尝试去 `pip install attention`
> 但最后遇到的是这样，表示没有这个`Attention`类
> 
> ```shell
> ImportError                               Traceback (most recent call last)
> <ipython-input-3-7affb3597aef> in <module>
>      14 from keras.layers import Embedding, Dense, Dropout, Bidirectional, CuDNNLSTM
>      15 from keras.layers import Add, Subtract, Multiply, Dot
> ---> 16 from attention import Attention
>      17 from keras import initializers, regularizers, constraints, optimizers, layers
>      18 from keras.preprocessing.sequence import pad_sequences
> 
> ImportError: cannot import name 'Attention' from 'attention' (/home/hello/.pyenv/versions/3.7.7/envs/env37rec/lib/python3.7/site-packages/attention/__init__.py)
> ```
> 
> 我也去源代码那里看了，确实是没有这个类的，因此我追踪`pypi`上的[模块](https://pypi.org/project/attention/#description)，也没能找到相关的。
> 
> 因此想问，我需要如何解决这个问题？

不好意思漏了，我刚上传了。

**Comment by nicken** [comment]
谢谢大佬！
